package com.example.paymentservice.Controller;

import com.example.paymentservice.dto.PaymentRequest;
import com.example.paymentservice.dto.PaymentResponse;
import com.example.paymentservice.entity.Payment;
import com.example.paymentservice.entity.PaymentStatus;
import com.example.paymentservice.repository.PaymentRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/payments")
public class PaymentController {

    @Autowired
    private PaymentRepository paymentRepository;

    @PostMapping
    public PaymentResponse processPayment(@RequestBody PaymentRequest request) {
        Payment payment = new Payment();
        // ID will be auto-generated by the DB, no need to set it
        payment.setOrderId(request.getOrderId());
        payment.setAmount(request.getAmount());
        payment.setPaymentMethod(request.getPaymentMethod());

        PaymentStatus status = request.getAmount() > 0 ? PaymentStatus.SUCCESS : PaymentStatus.FAILED;
        payment.setStatus(status);

        paymentRepository.save(payment);

        PaymentResponse response = new PaymentResponse();
        response.setStatus(status);
        return response;
    }
}
